In [1]:
%load_ext autoreload
%autoreload 2

import os, sys

sys.path.insert(0, "..")
from spec.enums import MainTableColumns as Cols, EventType

import pandas as pd

In [2]:
base_dir = '../../sample_data/edwards/raw/2019/'

In [3]:
keystrokes = pd.read_csv(os.path.join(base_dir, 'keystrokes.csv'))
keystrokes.head()

C:\Users\twprice\AppData\Local\Temp\ipykernel_17768\3859181010.py:1: DtypeWarning: Columns (12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  keystrokes = pd.read_csv(os.path.join(base_dir, 'keystrokes.csv'))

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1

In [4]:
keystrokes.EventType.value_counts()

EventType
File.Edit       5039755
Run.Program       75112
X-SwitchTask      12104
Submit             3326
Name: count, dtype: int64

In [5]:
keystrokes[keystrokes["X-Compilable"] == True]["X-RunHasError"].value_counts()

X-RunHasError
False    19547
True      4011
Name: count, dtype: int64

In [6]:
keystrokes[["X-RunHasError", "X-Compilable"]].value_counts()

X-RunHasError  X-Compilable
False          1               19547
True           0                7564
               1                4011
False          0                1875
Name: count, dtype: int64

In [7]:
def get_error_type(row):
    if row["X-Compilable"] == 0:
          return "SyntaxError"
    if row["X-RunHasError"] == True:
        return "Runtime Error"
    else:
        raise ValueError("Row does not have an error")

In [8]:
errors = keystrokes[(keystrokes[Cols.EventType] == EventType.RunProgram) & (keystrokes["X-RunHasError"] | (keystrokes["X-Compilable"] == 0))].copy()
errors[Cols.CompileMessageType] = errors.apply(get_error_type, axis=1)
errors

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CompileMessageType
8263,17015,S002,p4f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1568358538569,NaN,[],"[""SyntaxError: bad input on line 7""]",True,False,p4,f,0,SyntaxError
8445,17197,S002,p4f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1568358779040,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError
8447,17199,S002,p4f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1568358788939,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError
8451,17203,S002,p4f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1568358804780,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError
8459,17211,S002,p4f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1568358817854,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5129297,9181762,S516,p8f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1570829355186,NaN,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError
5129298,9181763,S516,p8f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1570829359590,NaN,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError
5129303,9181769,S516,p8f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1570833508356,NaN,[],"[""SyntaxError: bad input on line 41""]",True,False,p8,f,0,SyntaxError
5129522,9181989,S516,p8f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1570837312800,NaN,"[""stay""]","[""Your Door is #1!\n"", ""But behind Door #2 is ...",True,False,p8,f,1,Runtime Error
5129525,9181992,S516,p8f,task1.py,1,Run.Program,NaN,NaN,NaN,NaN,1570837331091,NaN,"[""stay""]","[""Your Door is #3!\n"", ""But behind Door #1 is ...",True,False,p8,f,1,Runtime Error

In [9]:
errors.CompileMessageType.value_counts()

CompileMessageType
SyntaxError      9439
Runtime Error    4011
Name: count, dtype: int64

In [10]:
errors[Cols.EventType] = EventType.CompileError
errors[Cols.ParentEventID] = errors[Cols.EventID].astype(str)
errors[Cols.EventID] = errors[Cols.EventID].astype(str) + "_parent"
errors

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,...,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CompileMessageType,ParentEventID
8263,17015_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 7""]",True,False,p4,f,0,SyntaxError,17015
8445,17197_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17197
8447,17199_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17199
8451,17203_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17203
8459,17211_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5129297,9181762_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError,9181762
5129298,9181763_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError,9181763
5129303,9181769_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 41""]",True,False,p8,f,0,SyntaxError,9181769
5129522,9181989_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,"[""stay""]","[""Your Door is #1!\n"", ""But behind Door #2 is ...",True,False,p8,f,1,Runtime Error,9181989
5129525,9181992_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,"[""stay""]","[""Your Door is #3!\n"", ""But behind Door #1 is ...",True,False,p8,f,1,Runtime Error,9181992

In [11]:
# Errors seem to just be syntax errors, no need to parse the output

# def parse_error(ouput):
#     try:
#         lst = eval(ouput)
#         return lst[-1]
#     except Exception as e:
#         return None

# errors[errors["X-Compilable"] == False]["X-RunOutput"].apply(parse_error).str[:5].value_counts()

In [12]:
keystrokes[Cols.CompileMessageType] = pd.NA
keystrokes[Cols.ParentEventID] = pd.NA
keystrokes[Cols.EventID] = keystrokes[Cols.EventID].astype(str)

In [13]:
events_with_errors = pd.concat([keystrokes, errors], ignore_index=True)

In [14]:
events_with_errors[events_with_errors.CompileMessageType.notna()].head()

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,...,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CompileMessageType,ParentEventID
5130297,17015_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 7""]",True,False,p4,f,0,SyntaxError,17015
5130298,17197_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17197
5130299,17199_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17199
5130300,17203_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17203
5130301,17211_parent,S002,p4f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,NaN,[],"[""SyntaxError: bad input on line 11""]",True,False,p4,f,0,SyntaxError,17211

In [15]:
errors.AssignmentID.value_counts()

AssignmentID
p8f    6128
p7f    3013
p6f    2815
p4f    1106
p5f     388
Name: count, dtype: int64

In [16]:
grades = pd.read_csv(os.path.join(base_dir, 'students.csv'))
link_subject_path = os.path.join(base_dir, '..', '..', '2019', 'LinkTables', 'Subject.csv')
# create dir if not exists
os.makedirs(os.path.dirname(link_subject_path), exist_ok=True)

grades.head()

,SubjectID,Group,SyntaxExercises,p4,p5,p6,p7,p8,exam1,exam2
0,S275,Spring,False,100.0,100,95.0,96.0,100.0,78.0,60.0
1,S047,Spring,False,100.0,100,95.0,100.0,100.0,82.0,80.0
2,S503,Spring,False,100.0,100,100.0,95.0,45.0,84.0,68.0
3,S032,Spring,False,50.0,90,44.0,98.0,60.0,46.0,50.0
4,S032,Fall,True,98.0,100,NaN,0.0,0.0,62.0,NaN

In [17]:
score_rows = grades.drop(columns=[Cols.SubjectID, "Group", "SyntaxExercises"])
shifted = score_rows.shift(axis=0)
same_as_last = (score_rows == shifted)
same_as_last = same_as_last.all(axis=1)

In [18]:
duplicated_subject_ids = grades[grades[[Cols.SubjectID, "Group"]].duplicated()][Cols.SubjectID].unique()
duplicated_subject_ids

array(['S516', 'S347', 'S496', 'S334', 'S352', 'S094', 'S456', 'S176',
       'S510', 'S265', 'S283', 'S391', 'S021', 'S461', 'S161', 'S245',
       'S286', 'S236'], dtype=object)

In [19]:
grades_deduped = grades[~same_as_last & ~grades[Cols.SubjectID].isin(duplicated_subject_ids)].copy()

grades_deduped.to_csv(link_subject_path, index=False)

In [20]:
grades.shape[0] - grades_deduped.shape[0]

58

In [21]:
grades_deduped[[Cols.SubjectID, "Group"]].duplicated().sum()

np.int64(0)

In [22]:
assignment_cols = [f"p{i}" for i in range(4, 8)]
assignment_grades = None
for semester in ["Fall", "Spring"]:
    semester_grades = grades_deduped[grades_deduped.Group == semester]
    melted_grades = semester_grades[[Cols.SubjectID] + assignment_cols].melt(id_vars=Cols.SubjectID, var_name=Cols.AssignmentID, value_name=Cols.Score)
    melted_grades["X-ClassID"] = semester
    melted_grades[Cols.AssignmentID] += semester[0].lower()  # e.g. p4 -> p4f, p5 -> p5f
    if assignment_grades is None:
        assignment_grades = melted_grades
    else:
        assignment_grades = pd.concat([assignment_grades, melted_grades], ignore_index=True)

assignment_grades

     SubjectID AssignmentID  Score X-ClassID
0         S032          p4f   98.0      Fall
1         S316          p4f  100.0      Fall
2         S029          p4f  100.0      Fall
3         S488          p4f  100.0      Fall
4         S216          p4f   96.0      Fall
...        ...          ...    ...       ...
1927      S079          p7s  100.0    Spring
1928      S324          p7s   40.0    Spring
1929      S018          p7s  100.0    Spring
1930      S480          p7s   95.0    Spring
1931      S457          p7s  100.0    Spring

[1932 rows x 4 columns]

In [23]:
assert assignment_grades[[Cols.AssignmentID, Cols.SubjectID]].value_counts().max() == 1

In [38]:
import numpy as np

submissions = keystrokes[keystrokes[Cols.EventType] == EventType.Submit]
last_submissions = submissions.loc[submissions.groupby([Cols.SubjectID, Cols.AssignmentID])[Cols.ClientTimestamp].idxmax()]
last_submissions = last_submissions[[Cols.EventID, Cols.AssignmentID, Cols.SubjectID]].copy()
last_submissions

         EventID AssignmentID SubjectID
1944        1948          p4s      S001
3075        3096          p5s      S001
7970       11799          p7s      S001
8622       17374          p4f      S002
10374      19126          p5f      S002
...          ...          ...       ...
5119604  9172061          p6f      S516
5119034  9171487          p6s      S516
5123215  9175676          p7f      S516
5123210  9175671          p7s      S516
5130296  9182763          p8f      S516

[1519 rows x 3 columns]

In [39]:
last_submissions.groupby([Cols.SubjectID, Cols.AssignmentID]).EventID.count().max()

np.int64(1)

In [40]:
last_submissions.AssignmentID.value_counts()

AssignmentID
p5s    180
p7f    179
p7s    176
p5f    170
p4f    170
p4s    147
p6f    137
p8s    128
p6s    123
p8f    109
Name: count, dtype: int64

In [41]:
last_submissions_with_grades = last_submissions.merge(assignment_grades, on=[Cols.SubjectID, Cols.AssignmentID], how='inner')
last_submissions_with_grades

      EventID AssignmentID SubjectID  Score X-ClassID
0        1948          p4s      S001  100.0    Spring
1        3096          p5s      S001  100.0    Spring
2       11799          p7s      S001  100.0    Spring
3       17374          p4f      S002   90.0      Fall
4       19126          p5f      S002   90.0      Fall
...       ...          ...       ...    ...       ...
1175  9100890          p7f      S512  100.0      Fall
1176  9114397          p5f      S513   80.0      Fall
1177  9118745          p6f      S513  100.0      Fall
1178  9123733          p7f      S513  100.0      Fall
1179  9131963          p5f      S514   90.0      Fall

[1180 rows x 5 columns]

In [42]:
keys_grades = set(assignment_grades[[Cols.SubjectID, Cols.AssignmentID]].itertuples(index=False, name=None))
keys_submissions = set(last_submissions[[Cols.SubjectID, Cols.AssignmentID]].itertuples(index=False, name=None))

print(keys_grades - keys_submissions)
print(keys_submissions - keys_grades)

{('S099', 'p6s'), ('S360', 'p5s'), ('S454', 'p7f'), ('S032', 'p5f'), ('S109', 'p5f'), ('S371', 'p6s'), ('S442', 'p7s'), ('S405', 'p6s'), ('S049', 'p6s'), ('S083', 'p4s'), ('S309', 'p4f'), ('S127', 'p6s'), ('S035', 'p5f'), ('S299', 'p6f'), ('S192', 'p7s'), ('S060', 'p6f'), ('S145', 'p5s'), ('S315', 'p4f'), ('S316', 'p4f'), ('S422', 'p7s'), ('S256', 'p4f'), ('S204', 'p6f'), ('S082', 'p4s'), ('S022', 'p7s'), ('S102', 'p5s'), ('S490', 'p7f'), ('S168', 'p7s'), ('S488', 'p6s'), ('S191', 'p4f'), ('S478', 'p4f'), ('S220', 'p7s'), ('S509', 'p6s'), ('S445', 'p6f'), ('S099', 'p7s'), ('S309', 'p5f'), ('S239', 'p5s'), ('S166', 'p6s'), ('S405', 'p7s'), ('S133', 'p6f'), ('S316', 'p5f'), ('S425', 'p4f'), ('S055', 'p4s'), ('S305', 'p6s'), ('S256', 'p5f'), ('S047', 'p4s'), ('S447', 'p5s'), ('S168', 'p5s'), ('S054', 'p6f'), ('S455', 'p7f'), ('S033', 'p6f'), ('S322', 'p5s'), ('S097', 'p7s'), ('S488', 'p4s'), ('S064', 'p6f'), ('S264', 'p5s'), ('S066', 'p4s'), ('S044', 'p6f'), ('S087', 'p6f'), ('S199', 'p7s'), ('S478', 'p5f'), ('S465', 'p7s'), ('S113', 'p6s'), ('S142', 'p6s'), ('S290', 'p6f'), ('S293', 'p7f'), ('S441', 'p6s'), ('S296', 'p4s'), ('S316', 'p4s'), ('S000', 'p4f'), ('S377', 'p6f'), ('S298', 'p6s'), ('S425', 'p5f'), ('S183', 'p6f'), ('S097', 'p5s'), ('S153', 'p6f'), ('S295', 'p6f'), ('S462', 'p6s'), ('S001', 'p6s'), ('S075', 'p7f'), ('S305', 'p7s'), ('S209', 'p6s'), ('S399', 'p5f'), ('S299', 'p4f'), ('S205', 'p6s'), ('S218', 'p5s'), ('S091', 'p7s'), ('S280', 'p7f'), ('S441', 'p4s'), ('S380', 'p5s'), ('S508', 'p6f'), ('S512', 'p6f'), ('S234', 'p5s'), ('S298', 'p4s'), ('S416', 'p6s'), ('S142', 'p7s'), ('S043', 'p5s'), ('S000', 'p5f'), ('S210', 'p6f'), ('S376', 'p4s'), ('S409', 'p6s'), ('S209', 'p4s'), ('S042', 'p6s'), ('S130', 'p7f'), ('S205', 'p4s'), ('S339', 'p6s'), ('S162', 'p4s'), ('S012', 'p4f'), ('S067', 'p6s'), ('S480', 'p7s'), ('S395', 'p7f'), ('S174', 'p6f'), ('S231', 'p7s'), ('S046', 'p6s'), ('S240', 'p4s'), ('S045', 'p6f'), ('S276', 'p5s'), ('S246', 'p4s'), ('S052', 'p4s'), ('S434', 'p6s'), ('S370', 'p4f'), ('S237', 'p6s'), ('S346', 'p6f'), ('S499', 'p6f'), ('S375', 'p6s'), ('S139', 'p6s'), ('S212', 'p6s'), ('S251', 'p7f'), ('S116', 'p7s'), ('S297', 'p6s'), ('S267', 'p7s'), ('S042', 'p4s'), ('S104', 'p6f'), ('S266', 'p6f'), ('S338', 'p5s'), ('S107', 'p7f'), ('S073', 'p6f'), ('S133', 'p5f'), ('S183', 'p4f'), ('S279', 'p6f'), ('S132', 'p5f'), ('S439', 'p6s'), ('S411', 'p6s'), ('S328', 'p6s'), ('S119', 'p4f'), ('S147', 'p4f'), ('S068', 'p6s'), ('S032', 'p7f'), ('S046', 'p4s'), ('S435', 'p4s'), ('S116', 'p5s'), ('S242', 'p4s'), ('S267', 'p5s'), ('S122', 'p6f'), ('S444', 'p4s'), ('S420', 'p5f'), ('S008', 'p6s'), ('S317', 'p4s'), ('S056', 'p7f'), ('S117', 'p4f'), ('S213', 'p5s'), ('S482', 'p6f'), ('S228', 'p7s'), ('S237', 'p7s'), ('S508', 'p4f'), ('S274', 'p4f'), ('S016', 'p4s'), ('S470', 'p5f'), ('S411', 'p4s'), ('S377', 'p5f'), ('S164', 'p6f'), ('S387', 'p6s'), ('S119', 'p5f'), ('S147', 'p5f'), ('S498', 'p4s'), ('S198', 'p4f'), ('S514', 'p4f'), ('S241', 'p7s'), ('S415', 'p7s'), ('S008', 'p4s'), ('S090', 'p4f'), ('S292', 'p6f'), ('S100', 'p7s'), ('S505', 'p7f'), ('S256', 'p7f'), ('S188', 'p4s'), ('S508', 'p5f'), ('S387', 'p4s'), ('S096', 'p7f'), ('S268', 'p6f'), ('S270', 'p5f'), ('S408', 'p6f'), ('S124', 'p7s'), ('S300', 'p4s'), ('S100', 'p5s'), ('S090', 'p5f'), ('S473', 'p6f'), ('S453', 'p7f'), ('S247', 'p6s'), ('S284', 'p7s'), ('S279', 'p4f'), ('S165', 'p7s'), ('S427', 'p5s'), ('S145', 'p6s'), ('S120', 'p7s'), ('S045', 'p5f'), ('S254', 'p5s'), ('S102', 'p6s'), ('S079', 'p7s'), ('S373', 'p6s'), ('S492', 'p6s'), ('S324', 'p5s'), ('S099', 'p4f'), ('S104', 'p5f'), ('S146', 'p4f'), ('S031', 'p6s'), ('S089', 'p7f'), ('S432', 'p7s'), ('S165', 'p5s'), ('S436', 'p5f'), ('S007', 'p5s'), ('S287', 'p6f'), ('S000', 'p7f'), ('S134', 'p4f'), ('S145', 'p4s'), ('S485', 'p4s'), ('S384', 'p6f'), ('S246', 'p7f'), ('S110', 'p6f'), ('S252', 'p6s'), ('S392', 'p6s'), ('S398', 'p4f'), ('S022', 'p6s'), ('S440', 'p4s'), ('S102', 'p4s'), ('S322', 'p6s'), ('S053', 'p7s'), ('S141', 'p7f'), ('S294', 'p4f'), ('S492', 'p4s'), ('S220', 'p6s'), ('S304', 'p4s'), ('S495', 'p4f'), ('S204', 'p7f'), ('S031', 'p4s'), ('S488', 'p4f'), ('S181', 'p5f'), ('S422', 'p4s'), ('S333', 'p5s'), ('S084', 'p6f'), ('S252', 'p4s'), ('S268', 'p4f'), ('S358', 'p6f'), ('S489', 'p5s'), ('S235', 'p5s'), ('S230', 'p6f'), ('S022', 'p4s'), ('S024', 'p6f'), ('S243', 'p7f'), ('S220', 'p4s'), ('S179', 'p6f'), ('S294', 'p5f'), ('S133', 'p7f'), ('S199', 'p6s'), ('S503', 'p6s'), ('S229', 'p6f'), ('S132', 'p7f'), ('S099', 'p4s'), ('S106', 'p7f'), ('S081', 'p4s'), ('S495', 'p5f'), ('S050', 'p6s'), ('S194', 'p7s'), ('S371', 'p4s'), ('S488', 'p5f'), ('S167', 'p5s'), ('S405', 'p4s'), ('S185', 'p6f'), ('S312', 'p6f'), ('S268', 'p5f'), ('S043', 'p6s'), ('S263', 'p5s'), ('S336', 'p6s'), ('S326', 'p6f'), ('S130', 'p7s'), ('S140', 'p7s'), ('S004', 'p6f'), ('S160', 'p6f'), ('S277', 'p6s'), ('S470', 'p7f'), ('S484', 'p6f'), ('S377', 'p7f'), ('S325', 'p5f'), ('S258', 'p7f'), ('S147', 'p7f'), ('S509', 'p4s'), ('S169', 'p5f'), ('S114', 'p6f'), ('S148', 'p6f'), ('S050', 'p7s'), ('S043', 'p4s'), ('S454', 'p6f'), ('S383', 'p4s'), ('S039', 'p5s'), ('S305', 'p4s'), ('S226', 'p6s'), ('S224', 'p4s'), ('S234', 'p7s'), ('S111', 'p5f'), ('S018', 'p6s'), ('S417', 'p5s'), ('S108', 'p7s'), ('S321', 'p6s'), ('S338', 'p6s'), ('S363', 'p7s'), ('S288', 'p7f'), ('S144', 'p4f'), ('S514', 'p7f'), ('S142', 'p4s'), ('S198', 'p7f'), ('S438', 'p7f'), ('S368', 'p7s'), ('S040', 'p5s'), ('S173', 'p5f'), ('S090', 'p7f'), ('S036', 'p4s'), ('S155', 'p4f'), ('S116', 'p6s'), ('S115', 'p5s'), ('S267', 'p6s'), ('S213', 'p6s'), ('S196', 'p6s'), ('S431', 'p5s'), ('S262', 'p7f'), ('S445', 'p4f'), ('S452', 'p5s'), ('S041', 'p5s'), ('S032', 'p5s'), ('S363', 'p5s'), ('S190', 'p6s'), ('S112', 'p7f'), ('S273', 'p6f'), ('S058', 'p7f'), ('S009', 'p7s'), ('S093', 'p6f'), ('S033', 'p4f'), ('S047', 'p5s'), ('S116', 'p4s'), ('S213', 'p4s'), ('S256', 'p7s'), ('S196', 'p4s'), ('S087', 'p4f'), ('S374', 'p7s'), ('S293', 'p6f'), ('S445', 'p5f'), ('S382', 'p6f'), ('S074', 'p4s'), ('S290', 'p4f'), ('S500', 'p5s'), ('S454', 'p4f'), ('S029', 'p4f'), ('S014', 'p7s'), ('S075', 'p6f'), ('S241', 'p6s'), ('S316', 'p5s'), ('S415', 'p6s'), ('S153', 'p4f'), ('S385', 'p6s'), ('S467', 'p7f'), ('S078', 'p7s'), ('S033', 'p5f'), ('S332', 'p6s'), ('S175', 'p6s'), ('S228', 'p4s'), ('S072', 'p6s'), ('S237', 'p4s'), ('S447', 'p6f'), ('S100', 'p6s'), ('S367', 'p6f'), ('S232', 'p4s'), ('S087', 'p5f'), ('S096', 'p5s'), ('S410', 'p6f'), ('S357', 'p7s'), ('S469', 'p5f'), ('S427', 'p6s'), ('S319', 'p7f'), ('S446', 'p5f'), ('S290', 'p5f'), ('S254', 'p6s'), ('S328', 'p4s'), ('S415', 'p4s'), ('S157', 'p4s'), ('S210', 'p4f'), ('S068', 'p4s'), ('S130', 'p6f'), ('S124', 'p6s'), ('S488', 'p7f'), ('S474', 'p7f'), ('S295', 'p5f'), ('S324', 'p6s'), ('S193', 'p5f'), ('S448', 'p7f'), ('S100', 'p4s'), ('S401', 'p5f'), ('S019', 'p7s'), ('S365', 'p6f'), ('S165', 'p6s'), ('S007', 'p6s'), ('S175', 'p7s'), ('S427', 'p4s'), ('S156', 'p6f'), ('S061', 'p7f'), ('S227', 'p4s'), ('S225', 'p7s'), ('S251', 'p6f'), ('S079', 'p6s'), ('S255', 'p7s'), ('S210', 'p5f'), ('S129', 'p6f'), ('S246', 'p5s'), ('S137', 'p7s'), ('S507', 'p7f'), ('S345', 'p7f'), ('S266', 'p4f'), ('S165', 'p4s'), ('S032', 'p6f'), ('S366', 'p7f'), ('S120', 'p4s'), ('S333', 'p6s'), ('S206', 'p4f'), ('S027', 'p5s'), ('S225', 'p5s'), ('S291', 'p6f'), ('S235', 'p6s'), ('S437', 'p5f'), ('S233', 'p5f'), ('S079', 'p4s'), ('S255', 'p5s'), ('S053', 'p6s'), ('S447', 'p4f'), ('S372', 'p7f'), ('S367', 'p4f'), ('S046', 'p5s'), ('S282', 'p6s'), ('S128', 'p5f'), ('S410', 'p4f'), ('S482', 'p4f'), ('S360', 'p4s'), ('S502', 'p7f'), ('S247', 'p4s'), ('S349', 'p7f'), ('S167', 'p6s'), ('S073', 'p5f'), ('S075', 'p6s'), ('S164', 'p4f'), ('S424', 'p7s'), ('S239', 'p6s'), ('S309', 'p6f'), ('S053', 'p4s'), ('S320', 'p6s'), ('S393', 'p6s'), ('S316', 'p6f'), ('S315', 'p6f'), ('S308', 'p7s'), ('S447', 'p5f'), ('S447', 'p6s'), ('S256', 'p6f'), ('S413', 'p6f'), ('S085', 'p5s'), ('S412', 'p7s'), ('S443', 'p5f'), ('S194', 'p6s'), ('S373', 'p4s'), ('S410', 'p5f'), ('S482', 'p5f'), ('S200', 'p4f'), ('S096', 'p6f'), ('S331', 'p7s'), ('S167', 'p4s'), ('S191', 'p6f'), ('S478', 'p6f'), ('S239', 'p4s'), ('S164', 'p5f'), ('S388', 'p6s'), ('S308', 'p5s'), ('S445', 'p7f'), ('S393', 'p4s'), ('S453', 'p6f'), ('S075', 'p7s'), ('S425', 'p6f'), ('S292', 'p5f'), ('S322', 'p4s'), ('S320', 'p7s'), ('S417', 'p6s'), ('S300', 'p5s'), ('S399', 'p6f'), ('S098', 'p5f'), ('S090', 'p7s'), ('S054', 'p7f'), ('S329', 'p5s'), ('S388', 'p4s'), ('S130', 'p4s'), ('S040', 'p6s'), ('S064', 'p7f'), ('S059', 'p4s'), ('S477', 'p6s'), ('S223', 'p5s'), ('S089', 'p6f'), ('S428', 'p6s'), ('S446', 'p7f'), ('S469', 'p7f'), ('S028', 'p4f'), ('S000', 'p6f'), ('S452', 'p6s'), ('S483', 'p7s'), ('S289', 'p4s'), ('S203', 'p5f'), ('S041', 'p6s'), ('S290', 'p7f'), ('S246', 'p6f'), ('S039', 'p7s'), ('S363', 'p6s'), ('S058', 'p7s'), ('S503', 'p4s'), ('S151', 'p6f'), ('S303', 'p5f'), ('S088', 'p6s'), ('S183', 'p7f'), ('S153', 'p7f'), ('S218', 'p4s'), ('S193', 'p7f'), ('S413', 'p4f'), ('S401', 'p7f'), ('S083', 'p7s'), ('S047', 'p6s'), ('S234', 'p4s'), ('S418', 'p5s'), ('S038', 'p4f'), ('S440', 'p5s'), ('S442', 'p5s'), ('S058', 'p5s'), ('S363', 'p4s'), ('S351', 'p4s'), ('S433', 'p6f'), ('S115', 'p7s'), ('S287', 'p5f'), ('S091', 'p4s'), ('S243', 'p6f'), ('S397', 'p7f'), ('S422', 'p5s'), ('S127', 'p7s'), ('S132', 'p6f'), ('S256', 'p6s'), ('S413', 'p5f'), ('S022', 'p5s'), ('S207', 'p7f'), ('S179', 'p4f'), ('S374', 'p6s'), ('S229', 'p4f'), ('S038', 'p5f'), ('S226', 'p4s'), ('S253', 'p6s'), ('S215', 'p6f'), ('S047', 'p7s'), ('S096', 'p6s'), ('S099', 'p5s'), ('S500', 'p4s'), ('S174', 'p7f'), ('S185', 'p4f'), ('S014', 'p6s'), ('S364', 'p6f'), ('S488', 'p7s'), ('S312', 'p4f'), ('S358', 'p5f'), ('S049', 'p5s'), ('S187', 'p4f'), ('S024', 'p5f'), ('S470', 'p6f'), ('S404', 'p6s'), ('S374', 'p4s'), ('S484', 'p4f'), ('S147', 'p6f'), ('S151', 'p4f'), ('S179', 'p5f'), ('S412', 'p6f'), ('S296', 'p7s'), ('S279', 'p7f'), ('S199', 'p5s'), ('S357', 'p6s'), ('S400', 'p6f'), ('S114', 'p4f'), ('S488', 'p5s'), ('S369', 'p4f'), ('S509', 'p5s'), ('S342', 'p6s'), ('S185', 'p5f'), ('S447', 'p7f'), ('S208', 'p6s'), ('S078', 'p4s'), ('S187', 'p5f'), ('S421', 'p4s'), ('S482', 'p7f'), ('S166', 'p5s'), ('S221', 'p4s'), ('S404', 'p4s'), ('S305', 'p5s'), ('S275', 'p6s'), ('S246', 'p6s'), ('S441', 'p7s'), ('S224', 'p5s'), ('S484', 'p5f'), ('S151', 'p5f'), ('S288', 'p6f'), ('S514', 'p6f'), ('S357', 'p4s'), ('S414', 'p6f'), ('S462', 'p7s'), ('S090', 'p6f'), ('S513', 'p4f'), ('S114', 'p5f'), ('S490', 'p4f'), ('S125', 'p5f'), ('S259', 'p5f'), ('S113', 'p5s'), ('S323', 'p6s'), ('S142', 'p5s'), ('S255', 'p6s'), ('S262', 'p6f'), ('S205', 'p7s'), ('S269', 'p7s'), ('S441', 'p5s'), ('S472', 'p5f'), ('S272', 'p4f'), ('S098', 'p7f'), ('S275', 'p4s'), ('S175', 'p4s'), ('S444', 'p6s'), ('S240', 'p7s'), ('S058', 'p6f'), ('S246', 'p7s'), ('S052', 'p7s'), ('S268', 'p7f'), ('S455', 'p4f'), ('S436', 'p6f'), ('S205', 'p5s'), ('S042', 'p7s'), ('S327', 'p6s'), ('S077', 'p6f'), ('S162', 'p5s'), ('S303', 'p7f'), ('S511', 'p6s'), ('S085', 'p6s'), ('S416', 'p5s'), ('S355', 'p4f'), ('S293', 'p4f'), ('S240', 'p5s'), ('S382', 'p4f'), ('S046', 'p7s'), ('S170', 'p7f'), ('S389', 'p7f'), ('S435', 'p7s'), ('S353', 'p6s'), ('S109', 'p6f'), ('S297', 'p7s'), ('S467', 'p6f'), ('S075', 'p4f'), ('S181', 'p6f'), ('S285', 'p4f'), ('S489', 'p6s'), ('S308', 'p6s'), ('S258', 'p5f'), ('S412', 'p6s'), ('S118', 'p4f'), ('S327', 'p7s'), ('S238', 'p6s'), ('S398', 'p6f'), ('S384', 'p7f'), ('S062', 'p4s'), ('S400', 'p5f'), ('S331', 'p6s'), ('S293', 'p5f'), ('S435', 'p5s'), ('S237', 'p5s'), ('S382', 'p5f'), ('S294', 'p6f'), ('S232', 'p5s'), ('S048', 'p6s'), ('S424', 'p4s'), ('S297', 'p5s'), ('S413', 'p7f'), ('S051', 'p6s'), ('S451', 'p6f'), ('S488', 'p6f'), ('S071', 'p6s'), ('S474', 'p6f'), ('S075', 'p5f'), ('S448', 'p6f'), ('S130', 'p4f'), ('S308', 'p4s'), ('S029', 'p7s'), ('S285', 'p5f'), ('S223', 'p6s'), ('S235', 'p4s'), ('S157', 'p5s'), ('S058', 'p4f'), ('S184', 'p6s'), ('S061', 'p6f'), ('S048', 'p4s'), ('S156', 'p4f'), ('S238', 'p7s'), ('S051', 'p4s'), ('S450', 'p4f'), ('S251', 'p4f'), ('S179', 'p7f'), ('S507', 'p6f'), ('S223', 'p4s'), ('S130', 'p5f'), ('S418', 'p6s'), ('S440', 'p6s'), ('S394', 'p5f'), ('S387', 'p5s'), ('S463', 'p4f'), ('S329', 'p7s'), ('S107', 'p4f'), ('S039', 'p6s'), ('S366', 'p6f'), ('S423', 'p6f'), ('S058', 'p5f'), ('S185', 'p7f'), ('S058', 'p6s'), ('S365', 'p5f'), ('S136', 'p7s'), ('S194', 'p4s'), ('S201', 'p5f'), ('S372', 'p6f'), ('S422', 'p6s'), ('S035', 'p4f'), ('S291', 'p4f'), ('S177', 'p4f'), ('S083', 'p6s'), ('S056', 'p4f'), ('S160', 'p7f'), ('S484', 'p7f'), ('S307', 'p6s'), ('S039', 'p4s'), ('S477', 'p5f'), ('S173', 'p6f'), ('S502', 'p6f'), ('S082', 'p6s'), ('S058', 'p4s'), ('S369', 'p7f'), ('S431', 'p6s')}
{('S321', 'p8s'), ('S260', 'p4f'), ('S506', 'p8s'), ('S466', 'p8s'), ('S231', 'p8s'), ('S510', 'p6f'), ('S292', 'p8f'), ('S286', 'p7f'), ('S395', 'p8f'), ('S486', 'p7s'), ('S475', 'p8f'), ('S271', 'p5s'), ('S260', 'p5f'), ('S138', 'p8s'), ('S481', 'p4f'), ('S067', 'p8s'), ('S129', 'p8f'), ('S408', 'p8f'), ('S228', 'p8s'), ('S434', 'p8s'), ('S402', 'p4s'), ('S232', 'p8s'), ('S381', 'p7f'), ('S020', 'p8f'), ('S177', 'p8f'), ('S386', 'p8s'), ('S245', 'p6f'), ('S170', 'p8f'), ('S415', 'p8s'), ('S385', 'p8s'), ('S328', 'p8s'), ('S157', 'p8s'), ('S068', 'p8s'), ('S332', 'p8s'), ('S337', 'p8f'), ('S195', 'p8f'), ('S310', 'p7s'), ('S226', 'p8f'), ('S449', 'p6f'), ('S260', 'p8f'), ('S407', 'p4s'), ('S347', 'p4f'), ('S290', 'p8s'), ('S227', 'p8s'), ('S315', 'p8f'), ('S505', 'p8f'), ('S256', 'p8f'), ('S310', 'p5s'), ('S359', 'p8s'), ('S284', 'p8s'), ('S096', 'p8f'), ('S478', 'p8f'), ('S003', 'p7f'), ('S390', 'p8s'), ('S138', 'p6s'), ('S347', 'p5f'), ('S079', 'p8s'), ('S466', 'p7s'), ('S149', 'p7s'), ('S247', 'p8s'), ('S312', 'p8f'), ('S149', 'p5s'), ('S449', 'p4f'), ('S476', 'p8s'), ('S302', 'p6s'), ('S114', 'p8f'), ('S167', 'p8s'), ('S125', 'p8f'), ('S290', 'p6s'), ('S245', 'p5f'), ('S263', 'p8s'), ('S516', 'p7s'), ('S260', 'p7f'), ('S449', 'p5f'), ('S301', 'p4s'), ('S220', 'p8s'), ('S475', 'p6f'), ('S286', 'p8f'), ('S513', 'p8f'), ('S515', 'p6f'), ('S059', 'p8s'), ('S290', 'p7s'), ('S370', 'p8f'), ('S420', 'p8f'), ('S289', 'p8s'), ('S481', 'p7f'), ('S364', 'p8f'), ('S182', 'p8s'), ('S422', 'p4f'), ('S218', 'p8s'), ('S076', 'p8s'), ('S343', 'p8s'), ('S380', 'p8s'), ('S258', 'p8f'), ('S234', 'p8s'), ('S428', 'p8s'), ('S426', 'p8s'), ('S336', 'p8s'), ('S117', 'p8f'), ('S355', 'p8f'), ('S271', 'p6s'), ('S186', 'p8s'), ('S285', 'p8f'), ('S118', 'p8f'), ('S276', 'p8s'), ('S226', 'p8s'), ('S414', 'p8f'), ('S347', 'p7f'), ('S271', 'p4s'), ('S009', 'p8s'), ('S063', 'p8s'), ('S149', 'p8s'), ('S025', 'p5s'), ('S116', 'p8s'), ('S267', 'p8s'), ('S096', 'p8s'), ('S201', 'p8f'), ('S156', 'p8f'), ('S077', 'p8f'), ('S074', 'p8s'), ('S078', 'p8s'), ('S516', 'p6f'), ('S121', 'p8s'), ('S221', 'p8s'), ('S017', 'p8s'), ('S357', 'p8s'), ('S181', 'p8f'), ('S496', 'p5s'), ('S134', 'p8f'), ('S208', 'p8s'), ('S291', 'p8f'), ('S056', 'p8f'), ('S504', 'p8f'), ('S241', 'p8s'), ('S019', 'p8s'), ('S495', 'p8f'), ('S072', 'p8s'), ('S344', 'p6f'), ('S474', 'p8f'), ('S427', 'p8s'), ('S286', 'p6f'), ('S466', 'p6s'), ('S510', 'p4f'), ('S316', 'p8f'), ('S254', 'p8s'), ('S124', 'p8s'), ('S325', 'p8f'), ('S169', 'p8f'), ('S250', 'p7f'), ('S381', 'p6f'), ('S062', 'p8s'), ('S422', 'p7f'), ('S015', 'p8s'), ('S402', 'p5s'), ('S432', 'p8s'), ('S424', 'p8s'), ('S236', 'p5f'), ('S340', 'p4f'), ('S080', 'p8s'), ('S516', 'p6s'), ('S489', 'p8s'), ('S105', 'p8f'), ('S025', 'p8s'), ('S246', 'p8f'), ('S409', 'p8f'), ('S331', 'p8s'), ('S318', 'p8f'), ('S217', 'p8f'), ('S299', 'p8f'), ('S141', 'p8f'), ('S491', 'p8s'), ('S135', 'p8s'), ('S510', 'p8f'), ('S144', 'p8f'), ('S516', 'p4s'), ('S278', 'p7f'), ('S204', 'p8f'), ('S037', 'p5s'), ('S155', 'p8f'), ('S344', 'p5f'), ('S348', 'p8s'), ('S290', 'p4s'), ('S133', 'p8f'), ('S012', 'p8f'), ('S418', 'p8s'), ('S054', 'p8f'), ('S359', 'p4s'), ('S341', 'p5s'), ('S461', 'p4f'), ('S245', 'p8f'), ('S029', 'p8f'), ('S180', 'p8f'), ('S083', 'p8s'), ('S161', 'p5f'), ('S119', 'p8f'), ('S313', 'p7s'), ('S452', 'p8s'), ('S361', 'p8f'), ('S351', 'p8s'), ('S088', 'p8s'), ('S508', 'p8f'), ('S512', 'p8f'), ('S406', 'p4f'), ('S313', 'p5s'), ('S023', 'p8f'), ('S210', 'p8f'), ('S397', 'p8f'), ('S055', 'p8s'), ('S047', 'p8s'), ('S198', 'p8f'), ('S257', 'p8s'), ('S301', 'p5s'), ('S510', 'p7f'), ('S233', 'p8f'), ('S250', 'p8f'), ('S152', 'p8f'), ('S135', 'p7s'), ('S256', 'p8s'), ('S236', 'p7f'), ('S104', 'p8f'), ('S266', 'p8f'), ('S475', 'p5f'), ('S422', 'p8f'), ('S206', 'p8f'), ('S515', 'p5f'), ('S034', 'p8f'), ('S443', 'p8f'), ('S462', 'p8s'), ('S340', 'p7f'), ('S209', 'p8s'), ('S099', 'p8f'), ('S146', 'p8f'), ('S101', 'p8f'), ('S205', 'p8s'), ('S069', 'p8f'), ('S164', 'p8f'), ('S162', 'p8s'), ('S347', 'p6f'), ('S356', 'p6s'), ('S449', 'p7f'), ('S398', 'p8f'), ('S240', 'p8s'), ('S409', 'p8s'), ('S294', 'p8f'), ('S318', 'p8s'), ('S042', 'p8s'), ('S451', 'p8f'), ('S339', 'p8s'), ('S323', 'p8s'), ('S362', 'p8f'), ('S137', 'p8s'), ('S161', 'p7f'), ('S473', 'p8f'), ('S242', 'p8s'), ('S375', 'p8s'), ('S139', 'p8s'), ('S317', 'p8s'), ('S297', 'p8s'), ('S202', 'p7s'), ('S402', 'p7s'), ('S281', 'p8f'), ('S016', 'p8s'), ('S313', 'p8s'), ('S327', 'p8s'), ('S219', 'p8s'), ('S037', 'p6s'), ('S366', 'p8f'), ('S149', 'p4s'), ('S085', 'p8s'), ('S202', 'p5s'), ('S008', 'p8s'), ('S110', 'p8f'), ('S158', 'p8s'), ('S407', 'p7s'), ('S188', 'p8s'), ('S516', 'p5f'), ('S396', 'p8f'), ('S468', 'p8s'), ('S308', 'p8s'), ('S038', 'p8f'), ('S341', 'p6s'), ('S286', 'p4f'), ('S460', 'p8f'), ('S407', 'p5s'), ('S230', 'p8f'), ('S475', 'p7f'), ('S229', 'p8f'), ('S515', 'p7f'), ('S184', 'p8s'), ('S002', 'p8f'), ('S286', 'p5f'), ('S516', 'p8f'), ('S485', 'p8s'), ('S145', 'p8s'), ('S466', 'p5s'), ('S313', 'p6s'), ('S422', 'p6f'), ('S326', 'p8f'), ('S138', 'p7s'), ('S484', 'p8f'), ('S033', 'p8f'), ('S102', 'p8s'), ('S271', 'p8s'), ('S457', 'p8s'), ('S192', 'p8s'), ('S138', 'p5s'), ('S468', 'p6s'), ('S392', 'p8s'), ('S022', 'p8s'), ('S153', 'p8f'), ('S295', 'p8f'), ('S082', 'p8s'), ('S278', 'p6f'), ('S081', 'p8s'), ('S302', 'p7s'), ('S214', 'p8f'), ('S248', 'p8f'), ('S127', 'p8s'), ('S135', 'p6s'), ('S003', 'p4f'), ('S025', 'p4s'), ('S302', 'p5s'), ('S207', 'p8f'), ('S161', 'p8f'), ('S131', 'p8f'), ('S261', 'p8s'), ('S310', 'p8s'), ('S381', 'p8f'), ('S268', 'p8s'), ('S166', 'p8s'), ('S383', 'p8s'), ('S003', 'p5f'), ('S305', 'p8s'), ('S224', 'p8s'), ('S516', 'p7f'), ('S501', 'p8s'), ('S496', 'p4s'), ('S113', 'p8s'), ('S142', 'p8s')}

In [45]:
keystrokes.groupby([Cols.SubjectID, Cols.AssignmentID]).apply(lambda x: sum(x[Cols.EventType] == "Submit")).value_counts()

C:\Users\twprice\AppData\Local\Temp\ipykernel_17768\3522922229.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  keystrokes.groupby([Cols.SubjectID, Cols.AssignmentID]).apply(lambda x: sum(x[Cols.EventType] == "Submit")).value_counts()

1     717
2     424
3     156
4      83
0      63
5      51
6      29
7      19
8      14
10     10
9       7
11      3
14      3
17      1
19      1
13      1
Name: count, dtype: int64

In [ ]:
events_with_errors_and_submits = events_with_errors.merge(
    last_submissions_with_grades[[Cols.EventID, "Score"]],
    on=[Cols.EventID], how='left')
events_with_errors_and_submits

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,...,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CompileMessageType,ParentEventID,Score
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,...,NaN,NaN,NaN,NaN,p4,f,1,NaN,NaN,NaN
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,...,NaN,NaN,NaN,NaN,p4,f,1,NaN,NaN,NaN
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,...,NaN,NaN,NaN,NaN,p4,f,1,NaN,NaN,NaN
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,...,NaN,NaN,NaN,NaN,p4,f,1,NaN,NaN,NaN
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,...,NaN,NaN,NaN,NaN,p4,f,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5143742,9181762_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError,9181762,NaN
5143743,9181763_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,[],"[""SyntaxError: bad input on line 48""]",True,False,p8,f,0,SyntaxError,9181763,NaN
5143744,9181769_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,[],"[""SyntaxError: bad input on line 41""]",True,False,p8,f,0,SyntaxError,9181769,NaN
5143745,9181989_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,"[""stay""]","[""Your Door is #1!\n"", ""But behind Door #2 is ...",True,False,p8,f,1,Runtime Error,9181989,NaN
5143746,9181992_parent,S516,p8f,task1.py,1,Compile.Error,NaN,NaN,NaN,NaN,...,"[""stay""]","[""Your Door is #3!\n"", ""But behind Door #1 is ...",True,False,p8,f,1,Runtime Error,9181992,NaN

In [34]:
events_with_errors_and_submits[events_with_errors_and_submits.EventType == "Submit"].Score.notna().value_counts()

Score
False    2147
True     1179
Name: count, dtype: int64

In [ ]:
# 403 attempts have not submission grade
# This is in small part (63) because there was no submit event
# Much larger part is due to dropping students from the gradebook
# But these will have no label anyway...
events_with_errors_and_submits.groupby([Cols.SubjectID, Cols.AssignmentID]).Score.apply(lambda x: sum(x.notna())).value_counts()

Score
1    1179
0     403
Name: count, dtype: int64

In [118]:
events_with_errors_and_submits[Cols.AssignmentID].isna().sum()

np.int64(0)

In [119]:
events_with_errors_and_submits["X-ClassID"] = events_with_errors_and_submits[Cols.AssignmentID].str[-1].map(lambda x: "Spring" if x == "s" else "Fall")
events_with_errors_and_submits["X-ClassID"].value_counts()

X-ClassID
Fall      2815083
Spring    2329882
Name: count, dtype: int64

In [120]:
events_with_errors_and_submits[Cols.CompileMessageType].value_counts()

CompileMessageType
SyntaxError      9439
Runtime Error    4011
Name: count, dtype: int64

In [121]:
events_with_errors_and_submits.to_csv(os.path.join(base_dir, '..', '..', '2019', 'MainTable.csv'), index=False)

In [10]:
def reconstruct(df):
    s = ''
    for _,row in df[df.EventType=='File.Edit'].iterrows():
        i = int(row.SourceLocation)
        insert = '' if pd.isna(row.InsertText) else row.InsertText
        delete = '' if pd.isna(row.DeleteText) else row.DeleteText
        s = s[:i] + insert + s[i+len(delete):]
    return s

In [19]:
def reconstruct_all(df, in_place=False):
    if not in_place:
        df = df.copy()
    codestates = []
    s = ''
    for _,row in df.iterrows():
        if row.EventType == 'File.Edit':
            i = int(row.SourceLocation)
            insert = '' if pd.isna(row.InsertText) else row.InsertText
            delete = '' if pd.isna(row.DeleteText) else row.DeleteText
            s = s[:i] + insert + s[i+len(delete):]
        codestates.append(s)
    df['CodeState'] = codestates
    return df

In [11]:
one_attempt = keystrokes[(keystrokes.SubjectID == "S000") & (keystrokes.AssignmentID == "p4f")]
one_attempt

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,1896,S000,p4f,task0.py,0,File.Edit,t,t,NaN,865.0,1568244374034,Insert,NaN,NaN,NaN,NaN,p4,f,0
1897,1897,S000,p4f,task0.py,0,File.Edit,space,,NaN,866.0,1568244374086,Insert,NaN,NaN,NaN,NaN,p4,f,0
1898,1898,S000,p4f,task0.py,0,File.Edit,i,i,NaN,867.0,1568244374182,Insert,NaN,NaN,NaN,NaN,p4,f,0
1899,1899,S000,p4f,task0.py,0,File.Edit,t,t,NaN,868.0,1568244374297,Insert,NaN,NaN,NaN,NaN,p4,f,0
1900,1900,S000,p4f,task0.py,0,File.Edit,.,.,NaN,869.0,1568244374402,Insert,NaN,NaN,NaN,NaN,p4,f,0

In [20]:
with_codestate = reconstruct_all(one_attempt)

with_codestate

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CodeState
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1,#
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1,# @
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,1896,S000,p4f,task0.py,0,File.Edit,t,t,NaN,865.0,1568244374034,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1897,1897,S000,p4f,task0.py,0,File.Edit,space,,NaN,866.0,1568244374086,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1898,1898,S000,p4f,task0.py,0,File.Edit,i,i,NaN,867.0,1568244374182,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1899,1899,S000,p4f,task0.py,0,File.Edit,t,t,NaN,868.0,1568244374297,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1900,1900,S000,p4f,task0.py,0,File.Edit,.,.,NaN,869.0,1568244374402,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...

In [22]:
for i in range(len(with_codestate)):
    if i % 100 == 0:
        print(with_codestate.iloc[i].CodeState)
        print('\n-------\n')

#

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fil

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fills all the points in the rubric
#his name is legalese-man
import turtle,
def create_circle()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fills all the points in the rubric
#his name is legalese-man
import turtle
def createCircl

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function crea
def createCircle

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Also a color
def createCircle(Size, col):

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Also colors
def createCircle(circleX, circlY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#fu
def createCircle(startX, startY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a la
def createCircle(startX, startY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# But you can call me
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#his name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.set

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, ra, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)



-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, radius, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        begin_fill()
    el
    turtle.circle(radius)
    if fill == True


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, radius, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        turtle.begin_fill()
    else:
        pass
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill
creat

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
def createCircle(stradius, color, fill):
    turtle.penup()
#   	turtle.setposition(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill
createCircle(0, 0, 5, "orange", yes)

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

from turtl

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(radius, color, fill):
#   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()

#createCircle(5, "orange", True)
turtle.forward(50)

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)



-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)

#Problem -- it really, REALLY doesn't like the turt

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)

#Problem -- it really, REALLY doesn't like the turtle module for some reason, and it doesn't like any of the commands I throw at it.

-------

In [ ]:
from spec.enums import MainTableColumns as Cols
from spec.spec_definition import PS2Versions
import pandas as pd

In [ ]:
from database.config import PS2DataConfig

spec = PS2Versions.v1_0.load()

data_config = PS2DataConfig.from_yaml("sample_data_configs/codebench2024.yaml", spec)