In [1]:
%load_ext autoreload
%autoreload 2

import os, sys

# sys.path.insert(0, "src")

import pandas as pd

In [8]:
base_dir = '../../sample_data/edwards/raw/2021/'
# base_dir = '../../sample_data/edwards/raw/2019/'

In [7]:
keystrokes = pd.read_csv(os.path.join(base_dir, 'keystrokes.csv'))
keystrokes.head()

C:\Users\twprice\AppData\Local\Temp\ipykernel_340\3859181010.py:1: DtypeWarning: Columns (12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  keystrokes = pd.read_csv(os.path.join(base_dir, 'keystrokes.csv'))

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1

In [4]:
keystrokes.EventType.value_counts()

EventType
File.Edit         971220
X-Keystroke       618843
X-Action          418541
Run.Program        54561
X-ReplayAction     16247
X-Paste             3856
X-Copy              3256
X-Attention         2342
Name: count, dtype: int64

In [60]:
keystrokes["X-RunHasError"].value_counts()

X-RunHasError
False    21422
True     11575
Name: count, dtype: int64

In [7]:
keystrokes.EventType.value_counts()

EventType
File.Edit         971220
X-Keystroke       618843
X-Action          418541
Run.Program        54561
X-ReplayAction     16247
X-Paste             3856
X-Copy              3256
X-Attention         2342
Name: count, dtype: int64

In [39]:
# read the first 100 lines of os.path.join(base_dir, 'runs1.csv') as a text file
# it's a large file, so we will read only the first 100 lines to memory
with open(os.path.join(base_dir, 'runs1.csv'), 'r') as f:
    for i in range(100):
        print(f.readline().strip())

SubjectID,AssignmentID,File,Action,RunID,NumOutputLines,Source,OutputDestination,Output,ClientTimestamp
Student1,Assign6,task1.py,r,5,8.0,PythonRunner,,,1634536696349.0
Student1,Assign6,,o,5,,,stdout,"Fluky Number : 155
",1634536696350.0
Student1,Assign6,,o,5,,,stdout,"Fluky Number : 168
",1634536696350.0
Student1,Assign6,,o,5,,,stdout,"Fluky Number : 357
",1634536696350.0
Student1,Assign6,,o,5,,,stdout,"Fluky Number : 580
",1634536696350.0
Student1,Assign6,,o,5,,,stdout,"Fluky Number : 1895
",1634536696405.0
Student1,Assign6,,o,5,,,stdout,"Total Time : 3.58 seconds
",1634536699842.0
Student1,Assign6,,o,5,,,stdout,"Total loops : 24990004
",1634536699842.0
Student1,Assign6,,o,5,,,system,"
Process finished with exit code 0
",1634536699851.0
Student1,Assign6,task2.py,r,5,8.0,PythonRunner,,,1634622332557.0
Student1,Assign6,,o,5,,,stdout,Press Enter to continue with the simulation.,1634622332566.0
Student1,Assign6,,o,5,,,stdout,"The zookeeper saw an elephant 3.05% of nights
",1634622339140.0
Student1,Assign6,,o,5,,,stdout,"The zookeeper saw both elephants 9.54% of the nights he saw elephants
",1634622339141.0
Student1,Assign6,,o,5,,,stdout,"The Zookeeper was wrong!
",1634622339141.0
Student1,Assign6,,o,5,,,stdout,"
",1634622339141.0
Student1,Assign6,,o,5,,,stdout,Would you like to run the simulation again? (yes/no),1634622339141.0
Student1,Assign6,,o,5,,,stdout,"Ok. Goodbye!
",1634622354905.0
Student1,Assign6,,o,5,,,system,"
Process finished with exit code 0
",1634622354931.0
Student1,Assign6,task1.py,r,6,7.0,PythonRunner,,,1634536893715.0
Student1,Assign6,,o,6,,,stdout,"Total Time : 3.27 seconds
",1634536896759.0
Student1,Assign6,,o,6,,,stdout,"Total loops : 24990004
",1634536896759.0
Student1,Assign6,,o,6,,,system,"
Process finished with exit code 0
",1634536896767.0
Student1,Assign6,task2.py,r,6,7.0,PythonRunner,,,1634622359017.0
Student1,Assign6,,o,6,,,stdout,"The zookeeper saw an elephant 3.05% of nights
",1634622365041.0
Student1,Assign6,,o,6,,,stdout,"The zookeeper saw both elephants 8.73% of the nights he saw elephants
",1634622365041.0
Student1,Assign6,,o,6,,,stdout,"The Zookeeper was wrong!
",1634622365041.0
Student1,Assign6,,o,6,,,stdout,"
",1634622365041.0
Student1,Assign6,,o,6,,,stdout,Would you like to run the simulation again? (yes/no),1634622365041.0
Student1,Assign6,,o,6,,,stdout,"Ok. Goodbye!
",1634622369249.0
Student1,Assign6,,o,6,,,system,"
Process finished with exit code 0
",1634622369271.0
Student1,Assign6,task1.py,r,7,7.0,PythonRunner,,,1634536956085.0
Student1,Assign6,,o,7,,,stdout,"Total Time : 3.37 seconds
",1634536959316.0
Student1,Assign6,,o,7,,,stdout,"Total loops : 24990004
",1634536959316.0
Student1,Assign6,,o,7,,,system,"
Process finished with exit code 0
",1634536959318.0
Student1,Assign6,task2.py,r,7,7.0,PythonRunner,,,1634622393996.0
Student1,Assign6,,o,7,,,stdout,"The zookeeper saw an elephant 3.05% of nights
",1634622395772.0
Student1,Assign6,,o,7,,,stdout,"The zookeeper saw both elephants 9.19% of the nights he saw elephants
",1634622395772.0
Student1,Assign6,,o,7,,,stdout,"The Zookeeper was wrong!
",1634622395772.0
Student1,Assign6,,o,7,,,stdout,"
",1634622395772.0
Student1,Assign6,,o,7,,,stdout,Would you like to run the simulation again? (yes/no): ,1634622395772.0
Student1,Assign6,,o,7,,,stdout,"Ok. Goodbye!
",1634622408857.0
Student1,Assign6,,o,7,,,system,"
Process finished with exit code 0
",1634622408875.0
Student1,Assign6,task1.py,r,8,7.0,PythonRunner,,,1634537292862.0
Student1,Assign6,,o,8,,,stdout,"Total Time : 3.38 seconds
",1634537296076.0
Student1,Assign6,,o,8,,,stdout,"Total loops : 24990004
",1634537296076.0
Student1,Assign6,,o,8,,,system,"
Process finished with exit code 0
",1634537296084.0
Student1,Assign6,task2.py,r,8,7.0,PythonRunner,,,1634622524717.0
Student1,Assign6,,o,8,,,stdout,"The zookeeper saw an elephant 3.03% of nights
",1634622526610.0
Student1,Assign6,,o,8,,,stdout,"The zookeeper saw both elephants 8.87% of the nights he saw elephants
",1634622526610.0
Student1,Assign6,,o,8,,,stdout,"The Zookeeper was wrong!
",1634622526610.0
Student1,Assign6,,o,8,,,stdout,"
",1634622526610.0
Student1,Assign6,,o,8,,,stdout,Would you like to run the simulation again? (yes/no): ,1634622526610.0
Student1,Assign6,,o,8,,,stdout,"Ok. Goodbye!

In [ ]:
runs1 = pd.read_csv(os.path.join(base_dir, 'runs1.csv'))

C:\Users\twprice\AppData\Local\Temp\ipykernel_27760\1732991408.py:1: DtypeWarning: Columns (2,6) have mixed types. Specify dtype option on import or set low_memory=False.
  runs1 = pd.read_csv(os.path.join(base_dir, 'runs1.csv'))

,SubjectID,AssignmentID,File,Action,RunID,NumOutputLines,Source,OutputDestination,Output,ClientTimestamp
0,Student1,Assign6,task1.py,r,5,8.0,PythonRunner,NaN,NaN,1.634537e+12
1,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 155\n,1.634537e+12
2,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 168\n,1.634537e+12
3,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 357\n,1.634537e+12
4,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 580\n,1.634537e+12

In [40]:
runs1.head(20)

,SubjectID,AssignmentID,File,Action,RunID,NumOutputLines,Source,OutputDestination,Output,ClientTimestamp
0,Student1,Assign6,task1.py,r,5,8.0,PythonRunner,NaN,NaN,1.634537e+12
1,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 155\n,1.634537e+12
2,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 168\n,1.634537e+12
3,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 357\n,1.634537e+12
4,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 580\n,1.634537e+12
5,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Fluky Number : 1895\n,1.634537e+12
6,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Total Time : 3.58 seconds\n,1.634537e+12
7,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Total loops : 24990004\n,1.634537e+12
8,Student1,Assign6,NaN,o,5,NaN,NaN,system,\nProcess finished with exit code 0\n,1.634537e+12
9,Student1,Assign6,task2.py,r,5,8.0,PythonRunner,NaN,NaN,1.634622e+12
10,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Press Enter to continue with the simulation.,1.634622e+12
11,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,The zookeeper saw an elephant 3.05% of nights\n,1.634622e+12
12,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,The zookeeper saw both elephants 9.54% of the ...,1.634622e+12
13,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,The Zookeeper was wrong!\n,1.634622e+12
14,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,\n,1.634622e+12
15,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Would you like to run the simulation again? (y...,1.634622e+12
16,Student1,Assign6,NaN,o,5,NaN,NaN,stdout,Ok. Goodbye!\n,1.634622e+12
17,Student1,Assign6,NaN,o,5,NaN,NaN,system,\nProcess finished with exit code 0\n,1.634622e+12
18,Student1,Assign6,task1.py,r,6,7.0,PythonRunner,NaN,NaN,1.634537e+12
19,Student1,Assign6,NaN,o,6,NaN,NaN,stdout,Total Time : 3.27 seconds\n,1.634537e+12

In [ ]:
current_run = None
rows = []
stderr = ''

subset = runs1[(runs1.Action == 'r') | (runs1.OutputDestination == 'stderr')]
for i, row in subset.iterrows():
    # print(row.Action, row.Action == 'r')
    if row.Action == 'r':
        if current_run is not None:
            current_run['stderr'] = stderr
            rows.append(current_run)
        current_run = row.to_dict()
        stderr = ''
        continue

    if row.OutputDestination == 'stderr':
        stderr += row.Output

runs = pd.DataFrame(rows)

In [57]:
runs[runs.stderr.str.len() > 0].stderr

11       Traceback (most recent call last):\n  File "ta...
31       Traceback (most recent call last):\n  File "fl...
32       Traceback (most recent call last):\n  File "fl...
33       Traceback (most recent call last):\n  File "fl...
39       Traceback (most recent call last):\n  File "ta...
                               ...
11569    Traceback (most recent call last):\n  File "me...
11574    Traceback (most recent call last):\n  File "me...
11575    Traceback (most recent call last):\n  File "me...
11576    Traceback (most recent call last):\n  File "me...
11577    Traceback (most recent call last):\n  File "me...
Name: stderr, Length: 4440, dtype: object

In [16]:
runs1[runs1.Source == "PythonRunner"].Output.isna().mean()

np.float64(1.0)

In [52]:
(runs1.OutputDestination == 'stderr').mean()

np.float64(0.00195840831490462)

In [27]:
runs1.NumOutputLines.value_counts()

NumOutputLines
1.0         851
0.0         572
10.0        491
5.0         446
8.0         417
           ...
100069.0      1
292.0         1
100070.0      1
221.0         1
305.0         1
Name: count, Length: 334, dtype: int64

In [38]:
runs1[~runs1.Output.isna()].Output.str.count('\n').mean()

np.float64(0.9967637136885001)

In [ ]:
runs1.NumOutputLines[~runs1.Output.isna()].value_counts()

NumOutputLines
1.0         851
0.0         572
10.0        491
5.0         446
8.0         417
           ...
100069.0      1
292.0         1
100070.0      1
221.0         1
305.0         1
Name: count, Length: 334, dtype: int64

In [26]:
output = runs1[runs1.OutputDestination == "stderr"].Output.reset_index()
for i in range(100):
    print(output.values[i][1])
    print('-' * 80)

Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task2.py", line 42, in <module>

--------------------------------------------------------------------------------
    userInput = input("Would you like to run the simulation again? (yes/no): ").lower()

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "flukytester.py", line 11, in <module>

--------------------------------------------------------------------------------
    number = int(input("Enter desired number to check: "))

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "flukytester.py", line 11, in <module>

--------------------------------------------------------------------------------
    number = int(input("Enter desired number to check: "))

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "flukytester.py", line 11, in <module>

--------------------------------------------------------------------------------
    number = int(input("Enter desired number to check: "))

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task2.py", line 13, in <module>

--------------------------------------------------------------------------------
    oneDumbo, twoDumbo = 0

--------------------------------------------------------------------------------
TypeError: cannot unpack non-iterable int object

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 8, in makeNumberPyramid

--------------------------------------------------------------------------------
    for i in range(0, rows):

--------------------------------------------------------------------------------
TypeError: 'str' object cannot be interpreted as an integer

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 8, in makeNumberPyramid

--------------------------------------------------------------------------------
    for i in range(0, rows):

--------------------------------------------------------------------------------
TypeError: 'str' object cannot be interpreted as an integer

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 12, in makeNumberPyramid

--------------------------------------------------------------------------------
    row += str(rows)

--------------------------------------------------------------------------------
TypeError: 'str' object is not callable

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 12, in makeNumberPyramid

--------------------------------------------------------------------------------
    row += rows

--------------------------------------------------------------------------------
TypeError: can only concatenate str (not "int") to str

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 12, in makeNumberPyramid

--------------------------------------------------------------------------------
    row += str(rows)

--------------------------------------------------------------------------------
TypeError: 'str' object is not callable

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 21, in <module>

--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
  File "task1.py", line 17, in main

--------------------------------------------------------------------------------
    def main():

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 24, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 21, in main

--------------------------------------------------------------------------------
    result = makeNumberPyramid(userInput)

--------------------------------------------------------------------------------
  File "task1.py", line 7, in makeNumberPyramid

--------------------------------------------------------------------------------
    maxLength = len(rowNum) * rowNum + rowNum - 1

--------------------------------------------------------------------------------
TypeError: object of type 'int' has no len()

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 25, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task1.py", line 21, in main

--------------------------------------------------------------------------------
    userInput = int(input("Enter number of desired rows: "))

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task2.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task2.py", line 8, in main

--------------------------------------------------------------------------------
    startX, startY = input("Please enter desired coordinates (x,y): ").split(",")

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task2.py", line 20, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------
  File "task2.py", line 18, in main

--------------------------------------------------------------------------------
    drawChessboard(startX, startY, eval(width), eval(height))

--------------------------------------------------------------------------------
  File "chessboard.py", line 58, in drawChessboard

--------------------------------------------------------------------------------
    turtle.done()

--------------------------------------------------------------------------------
  File "<string>", line 8, in mainloop

--------------------------------------------------------------------------------
  File "turtle.py", line 812, in mainloop

--------------------------------------------------------------------------------
    self.cv.tk.mainloop()

--------------------------------------------------------------------------------
KeyboardInterrupt

--------------------------------------------------------------------------------
Traceback (most recent call last):

--------------------------------------------------------------------------------
  File "task1.py", line 65, in <module>

--------------------------------------------------------------------------------
    main()

--------------------------------------------------------------------------------

In [10]:
def reconstruct(df):
    s = ''
    for _,row in df[df.EventType=='File.Edit'].iterrows():
        i = int(row.SourceLocation)
        insert = '' if pd.isna(row.InsertText) else row.InsertText
        delete = '' if pd.isna(row.DeleteText) else row.DeleteText
        s = s[:i] + insert + s[i+len(delete):]
    return s

In [19]:
def reconstruct_all(df, in_place=False):
    if not in_place:
        df = df.copy()
    codestates = []
    s = ''
    for _,row in df.iterrows():
        if row.EventType == 'File.Edit':
            i = int(row.SourceLocation)
            insert = '' if pd.isna(row.InsertText) else row.InsertText
            delete = '' if pd.isna(row.DeleteText) else row.DeleteText
            s = s[:i] + insert + s[i+len(delete):]
        codestates.append(s)
    df['CodeState'] = codestates
    return df

In [11]:
one_attempt = keystrokes[(keystrokes.SubjectID == "S000") & (keystrokes.AssignmentID == "p4f")]
one_attempt

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,1896,S000,p4f,task0.py,0,File.Edit,t,t,NaN,865.0,1568244374034,Insert,NaN,NaN,NaN,NaN,p4,f,0
1897,1897,S000,p4f,task0.py,0,File.Edit,space,,NaN,866.0,1568244374086,Insert,NaN,NaN,NaN,NaN,p4,f,0
1898,1898,S000,p4f,task0.py,0,File.Edit,i,i,NaN,867.0,1568244374182,Insert,NaN,NaN,NaN,NaN,p4,f,0
1899,1899,S000,p4f,task0.py,0,File.Edit,t,t,NaN,868.0,1568244374297,Insert,NaN,NaN,NaN,NaN,p4,f,0
1900,1900,S000,p4f,task0.py,0,File.Edit,.,.,NaN,869.0,1568244374402,Insert,NaN,NaN,NaN,NaN,p4,f,0

In [20]:
with_codestate = reconstruct_all(one_attempt)

with_codestate

,EventID,SubjectID,AssignmentID,CodeStateSection,X-Task,EventType,X-Keystroke,InsertText,DeleteText,SourceLocation,ClientTimestamp,EditType,X-RunInput,X-RunOutput,X-RunHasError,X-RunUserTerminated,X-RawAssignmentID,X-Term,X-Compilable,CodeState
0,0,S000,p4f,task0.py,0,File.Edit,#,#,NaN,0.0,1568242704669,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
1,1,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242704830,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
2,2,S000,p4f,task0.py,0,File.Edit,delete,NaN,,1.0,1568242705198,Delete,NaN,NaN,NaN,NaN,p4,f,1,#
3,3,S000,p4f,task0.py,0,File.Edit,space,,NaN,1.0,1568242705450,Insert,NaN,NaN,NaN,NaN,p4,f,1,#
4,4,S000,p4f,task0.py,0,File.Edit,@,@,NaN,2.0,1568242705692,Insert,NaN,NaN,NaN,NaN,p4,f,1,# @
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,1896,S000,p4f,task0.py,0,File.Edit,t,t,NaN,865.0,1568244374034,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1897,1897,S000,p4f,task0.py,0,File.Edit,space,,NaN,866.0,1568244374086,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1898,1898,S000,p4f,task0.py,0,File.Edit,i,i,NaN,867.0,1568244374182,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1899,1899,S000,p4f,task0.py,0,File.Edit,t,t,NaN,868.0,1568244374297,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...
1900,1900,S000,p4f,task0.py,0,File.Edit,.,.,NaN,869.0,1568244374402,Insert,NaN,NaN,NaN,NaN,p4,f,0,# @@@@@@@@@@@@@@@\n# But you can call me @@@@\...

In [22]:
for i in range(len(with_codestate)):
    if i % 100 == 0:
        print(with_codestate.iloc[i].CodeState)
        print('\n-------\n')

#

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fil

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fills all the points in the rubric
#his name is legalese-man
import turtle,
def create_circle()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically fills all the points in the rubric
#his name is legalese-man
import turtle
def createCircl

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function crea
def createCircle

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Also a color
def createCircle(Size, col):

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Also colors
def createCircle(circleX, circlY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#fu
def createCircle(startX, startY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# Assn # 4
#creates a snowman that technically meets all the points in the rubric
#his name is legalese-man
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a la
def createCircle(startX, startY, size, color, fill):
    turtle.penup()

-------

# @@@@@@@@@@@@@@@
# But you can call me
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#his name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.set

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as
def createCircle(startX, startY, size, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, ra, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)



-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, radius, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        begin_fill()
    el
    turtle.circle(radius)
    if fill == True


-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
#yeah there are a bunch of extra arguments but I'm too lazy to write multiple versions of the same function, cuz then it'd be just as much work as
#doing it all longhand.
def createCircle(startX, startY, radius, color, fill):
    turtle.penup()
   	turtle.goto(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        turtle.begin_fill()
    else:
        pass
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill
creat

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.
import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.
def createCircle(stradius, color, fill):
    turtle.penup()
#   	turtle.setposition(startX, startY)
    turtle.setcolor(color)
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill
createCircle(0, 0, 5, "orange", yes)

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

from turtl

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(radius, color, fill):
#   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()

#createCircle(5, "orange", True)
turtle.forward(50)

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)



-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)

#Problem -- it really, REALLY doesn't like the turt

-------

# @@@@@@@@@@@@@@@
# But you can call me @@@@
# Assn # 4
#Creates a snowman that technically meets all the points in the rubric
#His name is legalese-man.

Import turtle

#Create a function creates a circle.  Takes multiple sizes, and can be filled or not.  Basically a more beefed up version of the original turtle circle()
#function except that it's much beefier and is much, MUCH easier to work with. I'm a lazy man.

def createCircle(StartX, StartY, radius, color, fill):
   	turtle.setpos(startX, startY)
    turtle.setcolor(color)
    turtle.down()
    if fill == True:
        turtle.begin_fill()
    turtle.circle(radius)
    if fill == True:
        turtle.end_fill()
#test to create circle
createCircle(0, 0, 5, "orange", True)

#Problem -- it really, REALLY doesn't like the turtle module for some reason, and it doesn't like any of the commands I throw at it.

-------

In [ ]:
from spec.enums import MainTableColumns as Cols
from spec.spec_definition import PS2Versions
import pandas as pd

In [ ]:
from database.config import PS2DataConfig

spec = PS2Versions.v1_0.load()

data_config = PS2DataConfig.from_yaml("sample_data_configs/codebench2024.yaml", spec)