In [16]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import matplotlib.pyplot as plt
import os, sys

sys.path.insert(0, "../")

from spec.enums import MainTableColumns as Cols, EventType

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
base_dir = os.path.join("..", "..", "sample_data", "falconcode")
sqlite_path = os.path.join(base_dir, "raw", "falconcode.sqlite")
sqlalchemy_url = "sqlite:///" + sqlite_path
assert os.path.exists(sqlite_path), "SQLite file does not exist at path: " + sqlite_path

In [37]:
sqlite_output = os.path.join(base_dir, "falconcode.sqlite")
output_url = "sqlite:///" + sqlite_output

In [6]:
runs = pd.read_sql_table(
    "runs",
    sqlalchemy_url,
)

In [8]:
runs

,id,student_id,course_id,problem_id,timestamp,score,code_hash
0,1,6841f916-e8eb-40a8-ad96-486f030ebb96,3,Airstrike,2021-12-29 02:11:55,-1.0,4056437beff8be1bd548271a2c7b79e334adb832
1,2,35a78ee4-f99e-4914-a38c-fea25a3e1e8d,3,Airstrike,2021-12-28 15:16:43,-1.0,6965122b550742f95679bb64a9974af36b2e2e73
2,3,8e6da047-045a-4be3-ac88-f08854f793ef,3,Recon,2021-12-24 23:02:51,-1.0,3484f44d0d9fa81b2e73adbca37cef65a6a1e06e
3,4,8e6da047-045a-4be3-ac88-f08854f793ef,3,Recon,2021-12-24 23:02:47,0.0,3484f44d0d9fa81b2e73adbca37cef65a6a1e06e
4,5,3387d072-70ef-47b4-96b3-29b7440314f7,3,Airstrike,2021-12-24 04:06:39,-1.0,f13191146e17267a68ec072fc5c138150c475b32
...,...,...,...,...,...,...,...
1433318,1433319,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,2,a2_4_colon,2021-07-22 22:53:24,100.0,1062dfa20789add3b1329902b29b8f2e4bd5f5d7
1433319,1433320,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,2,a2_6_combat,2021-07-22 22:56:09,0.0,f7388d8a008482c9c8bcb211ee7edeb795978a25
1433320,1433321,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,2,a2_6_combat,2021-07-22 22:56:27,50.0,0047289b08bbd4413f5d8feb52b0cf48d9a19ac9
1433321,1433322,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,2,a2_6_combat,2021-07-22 22:56:57,100.0,d227c3ba4048217bed20787e54e3c2ede8aee929
1433322,1433323,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,2,a2_7_attack,2021-07-22 23:00:48,100.0,c9eebc8f5ab40c72e265099eb41d67903d90c78d

In [25]:
problems = pd.read_sql_table(
    "problems",
    sqlalchemy_url,
)
problems

,id,course_id,type,exam,prompt,testcase,max_score,input_str,input_cast,output,...,loop_elements,loop_nested,stat_calculate,file_read,file_write,list,list_2d,dictionary,item_set,tuple
0,a3_3_animals,2,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,1,0,0,0,0,1,0,0,0,0
1,a3_1_cargo,2,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\nimport random, m...",100.0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
2,a3_3_games,2,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
3,a3_4_heights,2,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,pex3,2,project,0,"<div>\n <h2 style=""text-align: center;"">Com...","from cs110 import autograder\r\nimport random,...",0.0,0,0,1,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,a1_1_icbm,4,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
657,a1_1_dorms,4,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\nimport random, m...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
658,a1_1_cadet,4,skill,1,<div><strong>PROBLEM STATEMENT:<br></strong></...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
659,a1_1_bases,4,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
660,a1_1_aircraft,4,skill,1,<div>\n<p>&nbsp;</p>\n<p>Write the Python code...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
column_mapping = {
    "id": Cols.ProblemID,
    "course_id": Cols.TermID,
}

term_mapping = {
    2: "Spring 2021",
    3: "Fall 2021",
    4: "Spring 2022",
    5: "Test Data", # Just 47 records; likely not real data
}

link_problems = problems.rename(columns=column_mapping)
link_problems[Cols.TermID] = link_problems[Cols.TermID].map(term_mapping)

link_problems.head()

,ProblemID,TermID,type,exam,prompt,testcase,max_score,input_str,input_cast,output,...,loop_elements,loop_nested,stat_calculate,file_read,file_write,list,list_2d,dictionary,item_set,tuple
0,a3_3_animals,Spring 2021,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,1,0,0,0,0,1,0,0,0,0
1,a3_1_cargo,Spring 2021,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\nimport random, m...",100.0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
2,a3_3_games,Spring 2021,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
3,a3_4_heights,Spring 2021,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,pex3,Spring 2021,project,0,"<div>\n <h2 style=""text-align: center;"">Com...","from cs110 import autograder\r\nimport random,...",0.0,0,0,1,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,a1_1_icbm,Spring 2022,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
657,a1_1_dorms,Spring 2022,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\nimport random, m...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
658,a1_1_cadet,Spring 2022,skill,1,<div><strong>PROBLEM STATEMENT:<br></strong></...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
659,a1_1_bases,Spring 2022,skill,1,<div>\n<p>&nbsp;</p>\n<p><strong>PROBLEM STATE...,"from cs110 import autograder\r\nimport random,...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
660,a1_1_aircraft,Spring 2022,skill,1,<div>\n<p>&nbsp;</p>\n<p>Write the Python code...,"#import cs110,\r\nimport random, math\r\nfrom ...",100.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
link_problems.to_sql("LinkProblem", output_url, if_exists="replace", index=False)

661

In [35]:
link_problems.max_score.value_counts()

max_score
100.0    654
0.0        7
Name: count, dtype: int64

In [32]:
link_problems[[Cols.ProblemID, Cols.TermID]].duplicated().sum()

np.int64(0)

In [36]:
import numpy as np

column_mapping = {
    "id": Cols.EventID,
    "student_id": Cols.SubjectID,
    "course_id": Cols.TermID,
    "problem_id": Cols.ProblemID,
    "timestamp": Cols.ServerTimestamp,
    "score": Cols.Score,
    "code_hash": Cols.CodeStateID,
}

main_table = runs.rename(columns=column_mapping)
main_table = main_table[main_table[Cols.TermID] != 5] # Drop test data from the last term
main_table[Cols.TermID] = main_table[Cols.TermID].map(term_mapping)
main_table[Cols.EventType] = np.where(main_table[Cols.Score] == -1, EventType.RunProgram, EventType.Submit)
main_table.loc[main_table[Cols.Score] == -1, Cols.Score] = None
main_table[Cols.Score] = main_table[Cols.Score] / 100

main_table

,EventID,SubjectID,TermID,ProblemID,ServerTimestamp,Score,CodeStateID,EventType
0,1,6841f916-e8eb-40a8-ad96-486f030ebb96,Fall 2021,Airstrike,2021-12-29 02:11:55,NaN,4056437beff8be1bd548271a2c7b79e334adb832,Run.Program
1,2,35a78ee4-f99e-4914-a38c-fea25a3e1e8d,Fall 2021,Airstrike,2021-12-28 15:16:43,NaN,6965122b550742f95679bb64a9974af36b2e2e73,Run.Program
2,3,8e6da047-045a-4be3-ac88-f08854f793ef,Fall 2021,Recon,2021-12-24 23:02:51,NaN,3484f44d0d9fa81b2e73adbca37cef65a6a1e06e,Run.Program
3,4,8e6da047-045a-4be3-ac88-f08854f793ef,Fall 2021,Recon,2021-12-24 23:02:47,0.0,3484f44d0d9fa81b2e73adbca37cef65a6a1e06e,Submit
4,5,3387d072-70ef-47b4-96b3-29b7440314f7,Fall 2021,Airstrike,2021-12-24 04:06:39,NaN,f13191146e17267a68ec072fc5c138150c475b32,Run.Program
...,...,...,...,...,...,...,...,...
1433318,1433319,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,Spring 2021,a2_4_colon,2021-07-22 22:53:24,1.0,1062dfa20789add3b1329902b29b8f2e4bd5f5d7,Submit
1433319,1433320,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,Spring 2021,a2_6_combat,2021-07-22 22:56:09,0.0,f7388d8a008482c9c8bcb211ee7edeb795978a25,Submit
1433320,1433321,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,Spring 2021,a2_6_combat,2021-07-22 22:56:27,0.5,0047289b08bbd4413f5d8feb52b0cf48d9a19ac9,Submit
1433321,1433322,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,Spring 2021,a2_6_combat,2021-07-22 22:56:57,1.0,d227c3ba4048217bed20787e54e3c2ede8aee929,Submit
1433322,1433323,8a9837cb-a545-4eaa-90b0-d7e37caeadb2,Spring 2021,a2_7_attack,2021-07-22 23:00:48,1.0,c9eebc8f5ab40c72e265099eb41d67903d90c78d,Submit

In [ ]:
main_table.to_sql("MainTable", output_url, if_exists="replace", index=False)

1433276

In [42]:
from spec.enums import CodeStatesTableColumns as CodeCols, CoreTables

column_mapping = {
    "hash": CodeCols.CodeStateID,
    "source_code": CodeCols.Code,
}

code_samples = pd.read_sql_table(
    "code_samples",
    sqlalchemy_url,
)
code_states = code_samples.rename(columns=column_mapping)
code_states

,CodeStateID,Code,redacted
0,00000491f2a5b7faec9e08df4b5c22b6204639bb,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,0
1,000019efe7d7fe307479fba33b1a821a39b15335,# --------------------------------------------...,0
2,00002b46a2a6348e6a584963050ac9f7cf0d7e72,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,0
3,00003b948ada9bf05852a250aaf330ecf4ffc848,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,0
4,0000403119d5ae02df95f638239b8d3733fa6f1c,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,0
...,...,...,...
1061703,ffff8c9dcea53f3c6929904b106acbde3088d75c,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,0
1061704,ffffb20092111020ee189bbe1514ae8c0e7150f5,# AUTOGRADER IMPORT REMOVED\nimport pythonGrap...,1
1061705,ffffbd3c617076d966fcd666f2d5bfc24bf5acc7,# AUTOGRADER IMPORT REMOVED\nimport math\n\n# ...,0
1061706,ffffd91cc4f5a46784f8aa6d03068bb2e876ab78,# AUTOGRADER IMPORT REMOVED\n\n# -------------...,1
1061707,ffffe9ea3ea96add0ae6d61fa2233fb57f9b1d27,#---------------------------------------------...,1

In [43]:
code_states.to_sql(CoreTables.CodeStates, output_url, if_exists="replace", index=False)

1061708

In [44]:
column_mapping = {
    "id": Cols.TermID,
}

courses = pd.read_sql_table(
    "courses",
    sqlalchemy_url,
)
link_term = courses.rename(columns=column_mapping)
link_term[Cols.TermID] = link_term[Cols.TermID].map(term_mapping)
link_term

        TermID   name semester  year
0  Spring 2021  CS110   Spring  2021
1    Fall 2021  CS110     Fall  2021
2  Spring 2022  CS110   Spring  2022

In [45]:
link_term.to_sql("LinkTerm", output_url, if_exists="replace", index=False)

3

In [46]:
column_mapping = {
    "id": Cols.SubjectID,
    "course_id": Cols.TermID,
}

students = pd.read_sql_table(
    "students",
    sqlalchemy_url,
)
students = students.rename(columns=column_mapping)
students[Cols.TermID] = students[Cols.TermID].map(term_mapping)
students

,SubjectID,TermID,stem_major,gender,ethnicity
0,000f96b7-ba0e-43ce-a5c3-c8fc0a6406f0,Fall 2021,-1,M,WHITE
1,004362ba-cb75-400b-a279-c9f54e3dde5d,Fall 2021,0,M,WHITE
2,007b3513-a877-44c0-b841-0a9ff14ef6b4,Fall 2021,1,M,WHITE
3,007b944d-77d2-457f-b0e8-81b2fd80dbf6,Fall 2021,0,M,ASIAN
4,007f6785-388a-4dee-8cc8-e1c903fd78e2,Spring 2021,1,F,WHITE
...,...,...,...,...,...
1571,ff432c98-bc60-44c5-94d0-06d8266d7613,Fall 2021,1,F,WHITE
1572,ff85550f-ff7f-4c86-b13e-c327c8d6defd,Spring 2022,1,M,WHITE
1573,ff9215d2-3ee5-4952-acab-2a619bdd59f9,Spring 2022,1,M,WHITE
1574,ff97afb3-c8cd-468a-857b-328868626a3c,Fall 2021,0,M,WHITE
1575,fff55e39-6318-4b99-beea-89f977596462,Spring 2022,1,F,WHITE

In [47]:
students.to_sql("LinkSubject", output_url, if_exists="replace", index=False)

1576